version: "3.8"

services:
  backend:
    build: ./todo-backend
    ports:
      - "3000:3000"
    networks:
      - todo-network

  frontend:
    build: ./todo-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge